name: build-docker-image

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: build container
      run: make docker

    ## TODO push to docker registry from here, once dockerHub is set up
